services:
  - type: web
    name: book-ai-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"  # Changed from 3.13 to 3.11 for better compatibility
      - key: PORT
        value: "10000"
      - key: ENVIRONMENT
        value: "production"