services:
  - type: web
    name: book-ai-backend
    env: python
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel cython==0.29.36
      pip install --no-build-isolation -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    build:
      pythonVersion: "3.11.8"  # Must be exactly this version