services:
  - type: web
    name: book-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    build:
      pythonVersion: 3.13
